### ISSUE TITLE
Unclear deployment documentation

### ISSUE THREAD

**Issue by bguise987** [neilnagarsheth/columbus-commons-events#1]
But how will UDeploy it?

**Comment by neilnagarsheth** [comment]
Hello @nix7drummer88,

**U** can simply **Deploy** it by following the guides on [IBM's webpage](https://www.reddit.com/r/devops/comments/4v5mli/udeploy_and_atlassian_tool/d5vvi65/).

Let me know if this helps at all.

**Comment by bguise987** [comment]
Ah yes thank you @neilnagarsheth, this helps a lot!
